# Generated by Django 6.0.4 on 2026-04-16 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=200)),
                ('ci', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tel_fijo', models.CharField(blank=True, max_length=20, null=True)),
                ('cel', models.CharField(blank=True, max_length=20, null=True)),
                ('tel_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.estado')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.estadocivil')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.nacionalidad')),
                ('salario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.salario')),
                ('tipo_contacto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.tipocontacto')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogos.turno')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_login', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='empleados.empleado')),
            ],
        ),
    ]
